version: '3.8'

services:
  db:
    container_name: 'pg_dev'
    image: postgres:16.2-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - networking
    restart: always
networks:
  networking:
    driver: bridge